POST http://localhost:3333/transactions
Content-Type: application/json

{
  "title": "Card payment",
  "amount": 500,
  "type": "debit"
}

###

GET http://localhost:3333/transactions

###

GET http://localhost:3333/transactions/b8d0d586-a05f-400f-bd1d-81118c65bee1