POST http://localhost:3333/transactions
Content-Type: application/json

{
  "title": "Card payment",
  "amount": 5000,
  "type": "credit"
}

###

GET http://localhost:3333/transactions

###

GET http://localhost:3333/transactions/06d7fe7f-e681-471c-920e-a1c03310e727

###

GET http://localhost:3333/transactions/summary